### ISSUE TITLE
[Question] When will this template avliable?

### ISSUE THREAD

**Issue by mahoshojoHCG** [DemerzelSun12/hitreport#1]
When will this template avliable? 2020 will end soon.

**Comment by DemerzelSun12** [comment]
随缘写，看心情

**Comment by DemerzelSun12** [comment]
> When will this template avliable? 2020 will end soon.

随缘写，看心情

**Comment by DemerzelSun12** [comment]
> When will this template avliable? 2020 will end soon.

Theoretically, it can be used now, do not rule out messy small bugs
